@setlocal enableextensions

@echo off

echo.ant mp 920 hl72ada setup and build...
echo.ant first the setup...
call ant -f _ant-buildfiles\ant-publish\build-hl72ada-mp-920.xml setup_920 >ant-setup.log
echo.ant done with the setup...
echo.ant now the build...
call ant -f _ant-buildfiles\ant-publish\build-hl72ada-mp-920.xml  >ant-build.log
echo.ant all done...

echo.Done
pause
