@setlocal enableextensions

@echo off

echo.ant MP9 3.0 ada2hl7 setup and build...
echo.doing setup ...
call ant -f _ant-buildfiles\ant-publish\build-ada2hl7-mp-930.xml setup_mp930 >ant-setup.log
echo.done with setup ...
echo.doing build ...
call ant -f _ant-buildfiles\ant-publish\build-ada2hl7-mp-930.xml >ant-build.log
echo.done with build ...
echo.doing schematronvalidate ...
call ant -f _ant-buildfiles\ant-publish\build-ada2hl7-mp-930.xml schematronvalidate_hl7_930>ant-schematronvalidate_hl7_930.log
echo.done with schematronvalidate ...
echo.doing schemavalidate ...
call ant -f _ant-buildfiles\ant-publish\build-ada2hl7-mp-930.xml schemavalidate_hl7_930>ant-schemavalidate_hl7_930.log
echo.done with schemavalidate ...

echo.Done
pause
