@setlocal enableextensions

@echo off


echo.ant mp9 30 ada2fhir-r4 
echo.setup ...
call ant -f _ant-buildfiles\ant-publish\build-ada2fhir-mp9-30.xml setup_30 >ant-setup.log
echo.done with setup ...
echo.build...
call ant -f _ant-buildfiles\ant-publish\build-ada2fhir-mp9-30.xml >ant-build.log
echo.done with build ...
echo.ant mp9 30 ada2fhir-r4 convert examples ...
call ant -f _ant-buildfiles\ant-publish\build-ada2fhir-mp9-30.xml convert_ada_2_fhir_30_examples >ant-examples.log
echo.done with examples ...
echo.doing schematronvalidate ...
call ant -f _ant-buildfiles\ant-publish\build-ada2fhir-mp9-30.xml schematronvalidate_fhir_30 > ant-schematronvalidate.log
echo.done with schematronvalidate ...
rem echo.doing schemavalidate ...
rem call ant -f _ant-buildfiles\ant-publish\build-ada2fhir-mp9-30.xml schemavalidate_fhir_30>ant-schemavalidate.log
rem echo.done with schemavalidate ...

echo.Done
pause
