#!bin/bash

echo ant mp9 30 ada2fhir-r4 
echo setup ...
ant -f _ant-buildfiles/ant-publish/build-ada2fhir-mp9-30.xml setup_30 >ant-setup.log
echo done with setup ...
echo build...
ant -f _ant-buildfiles/ant-publish/build-ada2fhir-mp9-30.xml >ant-build.log
echo done with build ...
echo doing schematronvalidate ...
ant -f _ant-buildfiles/ant-publish/build-ada2fhir-mp9-30.xml schematronvalidate_fhir_30 > ant-schematronvalidate.log
echo done with schematronvalidate ...
rem echo doing schemavalidate ...
rem ant -f _ant-buildfiles/ant-publish/build-ada2fhir-mp9-30.xml schemavalidate_fhir_30>ant-schemavalidate.log
rem echo done with schemavalidate ...

echo Done
