echo ant imm 2.0 ada2fhir-r4 build ...
echo >"`dirname "$0"`ant-build.log"
ant -l "`dirname "$0"`ant-build.log" -f "`dirname "$0"`/_ant-buildfiles/ant-publish/build-ada2fhir-imm-20.xml"
echo ant imm 2.0 ada2fhir-r4 copy results ...
ant -l "`dirname "$0"`ant-build.log" -f "`dirname "$0"`/_ant-buildfiles/ant-publish/build-ada2fhir-imm-20.xml" copy_result_to_testscripts
echo Done
