@setlocal enableextensions

@echo off

echo.ant mp 9 2.0 ada2hl7 setup and build...
echo.doing setup ...
call ant -f _ant-buildfiles\ant-publish\build-ada2hl7-mp-920.xml setup_mp920 >ant-setup.log
echo.done with setup ...
echo.doing build ...
call ant -f _ant-buildfiles\ant-publish\build-ada2hl7-mp-920.xml >ant-build.log
echo.done with build ...
echo.doing schematronvalidate ...
call ant -f _ant-buildfiles\ant-publish\build-ada2hl7-mp-920.xml schematronvalidate_hl7_920>ant-schematronvalidate_hl7_920.log
echo.done with schematronvalidate ...
echo.doing schemavalidate ...
call ant -f _ant-buildfiles\ant-publish\build-ada2hl7-mp-920.xml schemavalidate_hl7_920>ant-schemavalidate_hl7_920.log
echo.done with schemavalidate ...

echo.Done
pause
