@setlocal enableextensions

@echo off

echo.ant mp 920 hl72ada setup and roundtrip...
echo.ant first the setup...
call ant -f _ant-buildfiles\ant-publish\build-hl72ada-mp-920.xml setup_920 >ant-setup.log
echo.ant done with the setup...
echo.ant now the roundtrip...
call ant -f _ant-buildfiles\ant-publish\build-hl72ada-mp-920.xml roundtrip_hl7_2_ada_920 >ant-roundtrip.log
echo.ant all done...

echo.Done
pause
